export const UPDATE_INPUT_TEXT = 'UPDATE_INPUT_TEXT';
export const UPDATE_OUTPUT_TEXT = 'UPDATE_OUTPUT_TEXT';

export const UPDATE_CODE_TEXT = 'UPDATE_CODE_TEXT';

export const TOGGLE_PREVIEW_ON = 'TOGGLE_PREVIEW_ON';
export const TOGGLE_PREVIEW_OFF = 'TOGGLE_PREVIEW_OFF';

export const TOGGLE_MODULE_ACTIVE_ON = 'TOGGLE_MODULE_ACTIVE_ON';
export const TOGGLE_MODULE_ACTIVE_OFF = 'TOGGLE_MODULE_ACTIVE_OFF';

export const UPDATE_DELETIONS_PREVIEW = 'UPDATE_DELETIONS_PREVIEW';
export const UPDATE_ADDITIONS_PREVIEW = 'UPDATE_ADDITIONS_PREVIEW';